# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iot_api_client.models.arduino_arduinoconnections_v1 import ArduinoArduinoconnectionsV1

class TestArduinoArduinoconnectionsV1(unittest.TestCase):
    """ArduinoArduinoconnectionsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArduinoArduinoconnectionsV1:
        """Test ArduinoArduinoconnectionsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArduinoArduinoconnectionsV1`
        """
        model = ArduinoArduinoconnectionsV1()
        if include_optional:
            return ArduinoArduinoconnectionsV1(
                catm1 = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                cellular = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                eth = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                gsm = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                lora = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                nb = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                wifi = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ],
                wifiandsecret = [
                    iot_api_client.models.mediatype_identifier:_application/vnd/arduino/credentialsv1+json;_view=default.Mediatype identifier: application/vnd.arduino.credentialsv1+json; view=default(
                        friendly_name = '', 
                        max_length = 56, 
                        required = True, 
                        secret_name = '', 
                        sensitive = True, )
                    ]
            )
        else:
            return ArduinoArduinoconnectionsV1(
        )
        """

    def testArduinoArduinoconnectionsV1(self):
        """Test ArduinoArduinoconnectionsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
