# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iot_api_client.models.dashboardv3 import Dashboardv3

class TestDashboardv3(unittest.TestCase):
    """Dashboardv3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dashboardv3:
        """Test Dashboardv3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dashboardv3`
        """
        model = Dashboardv3()
        if include_optional:
            return Dashboardv3(
                cover_image = '',
                name = '0',
                pages = [
                    iot_api_client.models.pagepayload.pagepayload(
                        icon = '', 
                        id = '1d4decea-63eb-4ecd-b5fb-bb21f120d3d9', 
                        name = '0', 
                        position = 56, )
                    ],
                soft_deleted = True,
                widgets = [
                    iot_api_client.models.widgetv3.widgetv3(
                        height = 56, 
                        height_mobile = 56, 
                        id = '', 
                        name = '', 
                        options = { }, 
                        page_id = '0', 
                        type = '', 
                        variables = [
                            ''
                            ], 
                        width = 56, 
                        width_mobile = 56, 
                        x = 56, 
                        x_mobile = 56, 
                        y = 56, 
                        y_mobile = 56, )
                    ]
            )
        else:
            return Dashboardv3(
        )
        """

    def testDashboardv3(self):
        """Test Dashboardv3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
