# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iot_api_client.api.devices_v2_certs_api import DevicesV2CertsApi


class TestDevicesV2CertsApi(unittest.TestCase):
    """DevicesV2CertsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DevicesV2CertsApi()

    def tearDown(self) -> None:
        pass

    def test_devices_v2_certs_create(self) -> None:
        """Test case for devices_v2_certs_create

        create devices_v2_certs
        """
        pass

    def test_devices_v2_certs_delete(self) -> None:
        """Test case for devices_v2_certs_delete

        delete devices_v2_certs
        """
        pass

    def test_devices_v2_certs_list(self) -> None:
        """Test case for devices_v2_certs_list

        list devices_v2_certs
        """
        pass

    def test_devices_v2_certs_show(self) -> None:
        """Test case for devices_v2_certs_show

        show devices_v2_certs
        """
        pass

    def test_devices_v2_certs_update(self) -> None:
        """Test case for devices_v2_certs_update

        update devices_v2_certs
        """
        pass


if __name__ == '__main__':
    unittest.main()
