# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from iot_api_client.models.devicev2_otabinaryurl import Devicev2Otabinaryurl

class TestDevicev2Otabinaryurl(unittest.TestCase):
    """Devicev2Otabinaryurl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Devicev2Otabinaryurl:
        """Test Devicev2Otabinaryurl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Devicev2Otabinaryurl`
        """
        model = Devicev2Otabinaryurl()
        if include_optional:
            return Devicev2Otabinaryurl(
                var_async = True,
                binary_key = 'ota/z/AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJysota',
                expire_in_mins = 56
            )
        else:
            return Devicev2Otabinaryurl(
                binary_key = 'ota/z/AMDTMv2D2ylmgd10Z3UB6UkJSISSB512iz2DiJysota',
        )
        """

    def testDevicev2Otabinaryurl(self):
        """Test Devicev2Otabinaryurl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
