# coding: utf-8

"""
    Iot API

    Collection of all public API endpoints.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iot_api_client
from iot_api_client.api.devices_v2_metadata_api import DevicesV2MetadataApi  # noqa: E501
from iot_api_client.rest import ApiException


class TestDevicesV2MetadataApi(unittest.TestCase):
    """DevicesV2MetadataApi unit test stubs"""

    def setUp(self):
        self.api = iot_api_client.api.devices_v2_metadata_api.DevicesV2MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_devices_v2_metadata_delete(self):
        """Test case for devices_v2_metadata_delete

        delete devices_v2_metadata  # noqa: E501
        """
        pass

    def test_devices_v2_metadata_list(self):
        """Test case for devices_v2_metadata_list

        list devices_v2_metadata  # noqa: E501
        """
        pass

    def test_devices_v2_metadata_set(self):
        """Test case for devices_v2_metadata_set

        set devices_v2_metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
