# coding: utf-8

"""
    Iot API

    Collection of all public API endpoints.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iot_api_client
from iot_api_client.models.arduino_client import ArduinoClient  # noqa: E501
from iot_api_client.rest import ApiException


class TestArduinoClient(unittest.TestCase):
    """ArduinoClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArduinoClient(self):
        """Test ArduinoClient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iot_api_client.models.arduino_client.ArduinoClient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
