# coding: utf-8

"""
    Iot API

    Collection of all public API endpoints.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iot_api_client
from iot_api_client.api.lora_gw_v1_api import LoraGwV1Api  # noqa: E501
from iot_api_client.rest import ApiException


class TestLoraGwV1Api(unittest.TestCase):
    """LoraGwV1Api unit test stubs"""

    def setUp(self):
        self.api = iot_api_client.api.lora_gw_v1_api.LoraGwV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_lora_gw_v1_claim(self):
        """Test case for lora_gw_v1_claim

        claim lora_gw_v1  # noqa: E501
        """
        pass

    def test_lora_gw_v1_create(self):
        """Test case for lora_gw_v1_create

        create lora_gw_v1  # noqa: E501
        """
        pass

    def test_lora_gw_v1_delete(self):
        """Test case for lora_gw_v1_delete

        delete lora_gw_v1  # noqa: E501
        """
        pass

    def test_lora_gw_v1_show(self):
        """Test case for lora_gw_v1_show

        show lora_gw_v1  # noqa: E501
        """
        pass

    def test_lora_gw_v1_unclaim(self):
        """Test case for lora_gw_v1_unclaim

        unclaim lora_gw_v1  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
