# coding: utf-8

"""
    Arduino IoT Cloud API

     Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iot_api_client
from iot_api_client.api.things_v2_api import ThingsV2Api  # noqa: E501
from iot_api_client.rest import ApiException


class TestThingsV2Api(unittest.TestCase):
    """ThingsV2Api unit test stubs"""

    def setUp(self):
        self.api = iot_api_client.api.things_v2_api.ThingsV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_things_v2_create(self):
        """Test case for things_v2_create

        create things_v2  # noqa: E501
        """
        pass

    def test_things_v2_create_sketch(self):
        """Test case for things_v2_create_sketch

        createSketch things_v2  # noqa: E501
        """
        pass

    def test_things_v2_delete(self):
        """Test case for things_v2_delete

        delete things_v2  # noqa: E501
        """
        pass

    def test_things_v2_delete_sketch(self):
        """Test case for things_v2_delete_sketch

        deleteSketch things_v2  # noqa: E501
        """
        pass

    def test_things_v2_list(self):
        """Test case for things_v2_list

        list things_v2  # noqa: E501
        """
        pass

    def test_things_v2_show(self):
        """Test case for things_v2_show

        show things_v2  # noqa: E501
        """
        pass

    def test_things_v2_update(self):
        """Test case for things_v2_update

        update things_v2  # noqa: E501
        """
        pass

    def test_things_v2_update_sketch(self):
        """Test case for things_v2_update_sketch

        updateSketch things_v2  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
