# coding: utf-8

"""
    Arduino IoT Cloud API

     Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import iot_api_client
from iot_api_client.api.lora_devices_v1_api import LoraDevicesV1Api  # noqa: E501
from iot_api_client.rest import ApiException


class TestLoraDevicesV1Api(unittest.TestCase):
    """LoraDevicesV1Api unit test stubs"""

    def setUp(self):
        self.api = iot_api_client.api.lora_devices_v1_api.LoraDevicesV1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_lora_devices_v1_create(self):
        """Test case for lora_devices_v1_create

        create lora_devices_v1  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
