# coding: utf-8

"""
    Iot API

    Collection of all public API endpoints.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ArduinoDevicev1(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'certificate': 'str',
        'compressed': 'ArduinoCompressedv1',
        'href': 'str',
        'id': 'str',
        'name': 'str',
        'serial': 'str',
        'type': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'certificate': 'certificate',
        'compressed': 'compressed',
        'href': 'href',
        'id': 'id',
        'name': 'name',
        'serial': 'serial',
        'type': 'type',
        'user_id': 'user_id'
    }

    def __init__(self, certificate=None, compressed=None, href=None, id=None, name=None, serial=None, type=None, user_id=None):  # noqa: E501
        """ArduinoDevicev1 - a model defined in OpenAPI"""  # noqa: E501

        self._certificate = None
        self._compressed = None
        self._href = None
        self._id = None
        self._name = None
        self._serial = None
        self._type = None
        self._user_id = None
        self.discriminator = None

        if certificate is not None:
            self.certificate = certificate
        if compressed is not None:
            self.compressed = compressed
        self.href = href
        self.id = id
        if name is not None:
            self.name = name
        if serial is not None:
            self.serial = serial
        if type is not None:
            self.type = type
        self.user_id = user_id

    @property
    def certificate(self):
        """Gets the certificate of this ArduinoDevicev1.  # noqa: E501

        The attached certificate  # noqa: E501

        :return: The certificate of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate):
        """Sets the certificate of this ArduinoDevicev1.

        The attached certificate  # noqa: E501

        :param certificate: The certificate of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """

        self._certificate = certificate

    @property
    def compressed(self):
        """Gets the compressed of this ArduinoDevicev1.  # noqa: E501


        :return: The compressed of this ArduinoDevicev1.  # noqa: E501
        :rtype: ArduinoCompressedv1
        """
        return self._compressed

    @compressed.setter
    def compressed(self, compressed):
        """Sets the compressed of this ArduinoDevicev1.


        :param compressed: The compressed of this ArduinoDevicev1.  # noqa: E501
        :type: ArduinoCompressedv1
        """

        self._compressed = compressed

    @property
    def href(self):
        """Gets the href of this ArduinoDevicev1.  # noqa: E501

        The api reference of this device  # noqa: E501

        :return: The href of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this ArduinoDevicev1.

        The api reference of this device  # noqa: E501

        :param href: The href of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def id(self):
        """Gets the id of this ArduinoDevicev1.  # noqa: E501

        The arn of the device  # noqa: E501

        :return: The id of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ArduinoDevicev1.

        The arn of the device  # noqa: E501

        :param id: The id of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ArduinoDevicev1.  # noqa: E501

        The friendly name of the device  # noqa: E501

        :return: The name of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ArduinoDevicev1.

        The friendly name of the device  # noqa: E501

        :param name: The name of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def serial(self):
        """Gets the serial of this ArduinoDevicev1.  # noqa: E501

        The serial uuid of the device  # noqa: E501

        :return: The serial of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._serial

    @serial.setter
    def serial(self, serial):
        """Sets the serial of this ArduinoDevicev1.

        The serial uuid of the device  # noqa: E501

        :param serial: The serial of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """

        self._serial = serial

    @property
    def type(self):
        """Gets the type of this ArduinoDevicev1.  # noqa: E501

        The type of the device  # noqa: E501

        :return: The type of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ArduinoDevicev1.

        The type of the device  # noqa: E501

        :param type: The type of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def user_id(self):
        """Gets the user_id of this ArduinoDevicev1.  # noqa: E501

        The id of the user  # noqa: E501

        :return: The user_id of this ArduinoDevicev1.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ArduinoDevicev1.

        The id of the user  # noqa: E501

        :param user_id: The user_id of this ArduinoDevicev1.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArduinoDevicev1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
