# coding: utf-8

"""
    Iot API

    Collection of all public API endpoints.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UpdateLoraAppsV1Payload(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'apps': 'list[str]'
    }

    attribute_map = {
        'apps': 'apps'
    }

    def __init__(self, apps=None):  # noqa: E501
        """UpdateLoraAppsV1Payload - a model defined in OpenAPI"""  # noqa: E501

        self._apps = None
        self.discriminator = None

        if apps is not None:
            self.apps = apps

    @property
    def apps(self):
        """Gets the apps of this UpdateLoraAppsV1Payload.  # noqa: E501


        :return: The apps of this UpdateLoraAppsV1Payload.  # noqa: E501
        :rtype: list[str]
        """
        return self._apps

    @apps.setter
    def apps(self, apps):
        """Sets the apps of this UpdateLoraAppsV1Payload.


        :param apps: The apps of this UpdateLoraAppsV1Payload.  # noqa: E501
        :type: list[str]
        """

        self._apps = apps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateLoraAppsV1Payload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
