# coding: utf-8

"""
    Arduino IoT Cloud API

     Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from iot_api_client import schemas  # noqa: F401


class Devicev2Otabinaryurl(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "binary_key",
        }
        
        class properties:
            
            
            class binary_key(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    regex=[{
                        'pattern': r'^ota/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+.ota$',  # noqa: E501
                    }]
            _async = schemas.BoolSchema
            expire_in_mins = schemas.Int64Schema
            __annotations__ = {
                "binary_key": binary_key,
                "async": _async,
                "expire_in_mins": expire_in_mins,
            }
    
    binary_key: MetaOapg.properties.binary_key
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["binary_key"]) -> MetaOapg.properties.binary_key: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["async"]) -> MetaOapg.properties._async: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expire_in_mins"]) -> MetaOapg.properties.expire_in_mins: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["binary_key", "async", "expire_in_mins", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["binary_key"]) -> MetaOapg.properties.binary_key: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["async"]) -> typing.Union[MetaOapg.properties._async, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expire_in_mins"]) -> typing.Union[MetaOapg.properties.expire_in_mins, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["binary_key", "async", "expire_in_mins", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        binary_key: typing.Union[MetaOapg.properties.binary_key, str, ],
        expire_in_mins: typing.Union[MetaOapg.properties.expire_in_mins, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Devicev2Otabinaryurl':
        return super().__new__(
            cls,
            *_args,
            binary_key=binary_key,
            expire_in_mins=expire_in_mins,
            _configuration=_configuration,
            **kwargs,
        )
