# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from arduino_iot_rest.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from arduino_iot_rest.model.arduino_compressedv2 import ArduinoCompressedv2
from arduino_iot_rest.model.arduino_devicev2 import ArduinoDevicev2
from arduino_iot_rest.model.arduino_devicev2_cert import ArduinoDevicev2Cert
from arduino_iot_rest.model.arduino_devicev2_cert_collection import ArduinoDevicev2CertCollection
from arduino_iot_rest.model.arduino_devicev2_collection import ArduinoDevicev2Collection
from arduino_iot_rest.model.arduino_devicev2_event_properties import ArduinoDevicev2EventProperties
from arduino_iot_rest.model.arduino_devicev2_pass import ArduinoDevicev2Pass
from arduino_iot_rest.model.arduino_devicev2_simple_properties import ArduinoDevicev2SimpleProperties
from arduino_iot_rest.model.arduino_devicev2_simple_properties_collection import ArduinoDevicev2SimplePropertiesCollection
from arduino_iot_rest.model.arduino_devicev2_webhook import ArduinoDevicev2Webhook
from arduino_iot_rest.model.arduino_devicev2_webhook_collection import ArduinoDevicev2WebhookCollection
from arduino_iot_rest.model.arduino_devicev2properties import ArduinoDevicev2properties
from arduino_iot_rest.model.arduino_devicev2propertyvalue import ArduinoDevicev2propertyvalue
from arduino_iot_rest.model.arduino_devicev2propertyvalue_collection import ArduinoDevicev2propertyvalueCollection
from arduino_iot_rest.model.arduino_devicev2propertyvalue_value import ArduinoDevicev2propertyvalueValue
from arduino_iot_rest.model.arduino_devicev2propertyvalue_value_statistics import ArduinoDevicev2propertyvalueValueStatistics
from arduino_iot_rest.model.arduino_devicev2propertyvalues import ArduinoDevicev2propertyvalues
from arduino_iot_rest.model.arduino_devicev2propertyvalues_last_evaluated_key import ArduinoDevicev2propertyvaluesLastEvaluatedKey
from arduino_iot_rest.model.arduino_property import ArduinoProperty
from arduino_iot_rest.model.arduino_property_collection import ArduinoPropertyCollection
from arduino_iot_rest.model.arduino_series_batch import ArduinoSeriesBatch
from arduino_iot_rest.model.arduino_series_raw_batch import ArduinoSeriesRawBatch
from arduino_iot_rest.model.arduino_series_raw_batch_lastvalue import ArduinoSeriesRawBatchLastvalue
from arduino_iot_rest.model.arduino_series_raw_last_value_response import ArduinoSeriesRawLastValueResponse
from arduino_iot_rest.model.arduino_series_raw_response import ArduinoSeriesRawResponse
from arduino_iot_rest.model.arduino_series_response import ArduinoSeriesResponse
from arduino_iot_rest.model.arduino_thing import ArduinoThing
from arduino_iot_rest.model.arduino_thing_collection import ArduinoThingCollection
from arduino_iot_rest.model.batch_last_value_requests_media_v1 import BatchLastValueRequestsMediaV1
from arduino_iot_rest.model.batch_query_raw_last_value_request_media_v1 import BatchQueryRawLastValueRequestMediaV1
from arduino_iot_rest.model.batch_query_raw_request_media_v1 import BatchQueryRawRequestMediaV1
from arduino_iot_rest.model.batch_query_raw_requests_media_v1 import BatchQueryRawRequestsMediaV1
from arduino_iot_rest.model.batch_query_raw_response_series_media_v1 import BatchQueryRawResponseSeriesMediaV1
from arduino_iot_rest.model.batch_query_request_media_v1 import BatchQueryRequestMediaV1
from arduino_iot_rest.model.batch_query_requests_media_v1 import BatchQueryRequestsMediaV1
from arduino_iot_rest.model.check_devices_v2_pass_payload import CheckDevicesV2PassPayload
from arduino_iot_rest.model.create_devices_v2_certs_payload import CreateDevicesV2CertsPayload
from arduino_iot_rest.model.create_devices_v2_payload import CreateDevicesV2Payload
from arduino_iot_rest.model.create_things_v2_payload import CreateThingsV2Payload
from arduino_iot_rest.model.devicev2 import Devicev2
from arduino_iot_rest.model.devicev2_cert import Devicev2Cert
from arduino_iot_rest.model.devicev2_pass import Devicev2Pass
from arduino_iot_rest.model.error import Error
from arduino_iot_rest.model.model_property import ModelProperty
from arduino_iot_rest.model.properties_value import PropertiesValue
from arduino_iot_rest.model.properties_values import PropertiesValues
from arduino_iot_rest.model.property_value import PropertyValue
from arduino_iot_rest.model.thing import Thing
from arduino_iot_rest.model.thing_sketch import ThingSketch
from arduino_iot_rest.model.update_sketch import UpdateSketch
