name: Publish package

on:
  push:
    tags:
      - 'v[0-9].*'

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build package
        run: |
          pip install -r requirements.txt
          pip install -U wheel
          pip install -U setuptools
          python setup.py bdist_wheel

      - name: Upload packate to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}