# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from iot_api_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from iot_api_client.model.arduino_compressedv2 import ArduinoCompressedv2
from iot_api_client.model.arduino_dashboardowner import ArduinoDashboardowner
from iot_api_client.model.arduino_dashboardshare import ArduinoDashboardshare
from iot_api_client.model.arduino_dashboardshare_collection import ArduinoDashboardshareCollection
from iot_api_client.model.arduino_dashboardv2 import ArduinoDashboardv2
from iot_api_client.model.arduino_dashboardv2_collection import ArduinoDashboardv2Collection
from iot_api_client.model.arduino_devicev2 import ArduinoDevicev2
from iot_api_client.model.arduino_devicev2_cert import ArduinoDevicev2Cert
from iot_api_client.model.arduino_devicev2_cert_collection import ArduinoDevicev2CertCollection
from iot_api_client.model.arduino_devicev2_collection import ArduinoDevicev2Collection
from iot_api_client.model.arduino_devicev2_event_properties import ArduinoDevicev2EventProperties
from iot_api_client.model.arduino_devicev2_pass import ArduinoDevicev2Pass
from iot_api_client.model.arduino_devicev2_simple_properties import ArduinoDevicev2SimpleProperties
from iot_api_client.model.arduino_devicev2_simple_properties_collection import ArduinoDevicev2SimplePropertiesCollection
from iot_api_client.model.arduino_devicev2_webhook import ArduinoDevicev2Webhook
from iot_api_client.model.arduino_devicev2_webhook_collection import ArduinoDevicev2WebhookCollection
from iot_api_client.model.arduino_devicev2properties import ArduinoDevicev2properties
from iot_api_client.model.arduino_devicev2propertyvalue import ArduinoDevicev2propertyvalue
from iot_api_client.model.arduino_devicev2propertyvalue_collection import ArduinoDevicev2propertyvalueCollection
from iot_api_client.model.arduino_devicev2propertyvalues import ArduinoDevicev2propertyvalues
from iot_api_client.model.arduino_linkedvariable import ArduinoLinkedvariable
from iot_api_client.model.arduino_linkedvariable_collection import ArduinoLinkedvariableCollection
from iot_api_client.model.arduino_loradevicev1 import ArduinoLoradevicev1
from iot_api_client.model.arduino_lorafreqplansv1 import ArduinoLorafreqplansv1
from iot_api_client.model.arduino_lorafreqplanv1 import ArduinoLorafreqplanv1
from iot_api_client.model.arduino_property import ArduinoProperty
from iot_api_client.model.arduino_property_collection import ArduinoPropertyCollection
from iot_api_client.model.arduino_series_batch import ArduinoSeriesBatch
from iot_api_client.model.arduino_series_raw_batch import ArduinoSeriesRawBatch
from iot_api_client.model.arduino_series_raw_batch_lastvalue import ArduinoSeriesRawBatchLastvalue
from iot_api_client.model.arduino_series_raw_last_value_response import ArduinoSeriesRawLastValueResponse
from iot_api_client.model.arduino_series_raw_response import ArduinoSeriesRawResponse
from iot_api_client.model.arduino_series_response import ArduinoSeriesResponse
from iot_api_client.model.arduino_tags import ArduinoTags
from iot_api_client.model.arduino_thing import ArduinoThing
from iot_api_client.model.arduino_thing_collection import ArduinoThingCollection
from iot_api_client.model.arduino_timeseriesmedia import ArduinoTimeseriesmedia
from iot_api_client.model.arduino_timezone import ArduinoTimezone
from iot_api_client.model.arduino_variableslinks import ArduinoVariableslinks
from iot_api_client.model.arduino_widgetv2 import ArduinoWidgetv2
from iot_api_client.model.arduino_widgetv2_collection import ArduinoWidgetv2Collection
from iot_api_client.model.batch_last_value_requests_media_v1 import BatchLastValueRequestsMediaV1
from iot_api_client.model.batch_query_raw_last_value_request_media_v1 import BatchQueryRawLastValueRequestMediaV1
from iot_api_client.model.batch_query_raw_request_media_v1 import BatchQueryRawRequestMediaV1
from iot_api_client.model.batch_query_raw_requests_media_v1 import BatchQueryRawRequestsMediaV1
from iot_api_client.model.batch_query_raw_response_series_media_v1 import BatchQueryRawResponseSeriesMediaV1
from iot_api_client.model.batch_query_request_media_v1 import BatchQueryRequestMediaV1
from iot_api_client.model.batch_query_requests_media_v1 import BatchQueryRequestsMediaV1
from iot_api_client.model.check_devices_v2_pass_payload import CheckDevicesV2PassPayload
from iot_api_client.model.create_devices_v2_certs_payload import CreateDevicesV2CertsPayload
from iot_api_client.model.create_devices_v2_payload import CreateDevicesV2Payload
from iot_api_client.model.create_lora_devices_v1_payload import CreateLoraDevicesV1Payload
from iot_api_client.model.dashboardshare import Dashboardshare
from iot_api_client.model.dashboardv2 import Dashboardv2
from iot_api_client.model.devicev2 import Devicev2
from iot_api_client.model.devicev2_cert import Devicev2Cert
from iot_api_client.model.devicev2_otabinaryurl import Devicev2Otabinaryurl
from iot_api_client.model.devicev2_pass import Devicev2Pass
from iot_api_client.model.error import Error
from iot_api_client.model.historic_data_request import HistoricDataRequest
from iot_api_client.model.model_property import ModelProperty
from iot_api_client.model.properties_value import PropertiesValue
from iot_api_client.model.properties_values import PropertiesValues
from iot_api_client.model.property_value import PropertyValue
from iot_api_client.model.sharerequest import Sharerequest
from iot_api_client.model.tag import Tag
from iot_api_client.model.thing_create import ThingCreate
from iot_api_client.model.thing_sketch import ThingSketch
from iot_api_client.model.thing_update import ThingUpdate
from iot_api_client.model.timeseries_data_point import TimeseriesDataPoint
from iot_api_client.model.update_sketch import UpdateSketch
from iot_api_client.model.widget import Widget
from iot_api_client.model.widgetlink import Widgetlink
