# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from iot_api_client.models.arduino_credentialsv1 import ArduinoCredentialsv1
from typing import Optional, Set
from typing_extensions import Self

class ArduinoArduinoconnectionsV1(BaseModel):
    """
    ArduinoArduinoconnectionsV1 media type (default view)
    """ # noqa: E501
    catm1: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    cellular: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    eth: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    gsm: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    lora: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    nb: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    wifi: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    wifiandsecret: Optional[List[ArduinoCredentialsv1]] = Field(default=None, description="ArduinoCredentialsv1Collection is the media type for an array of ArduinoCredentialsv1 (default view)")
    __properties: ClassVar[List[str]] = ["catm1", "cellular", "eth", "gsm", "lora", "nb", "wifi", "wifiandsecret"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArduinoArduinoconnectionsV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in catm1 (list)
        _items = []
        if self.catm1:
            for _item_catm1 in self.catm1:
                if _item_catm1:
                    _items.append(_item_catm1.to_dict())
            _dict['catm1'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cellular (list)
        _items = []
        if self.cellular:
            for _item_cellular in self.cellular:
                if _item_cellular:
                    _items.append(_item_cellular.to_dict())
            _dict['cellular'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in eth (list)
        _items = []
        if self.eth:
            for _item_eth in self.eth:
                if _item_eth:
                    _items.append(_item_eth.to_dict())
            _dict['eth'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in gsm (list)
        _items = []
        if self.gsm:
            for _item_gsm in self.gsm:
                if _item_gsm:
                    _items.append(_item_gsm.to_dict())
            _dict['gsm'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lora (list)
        _items = []
        if self.lora:
            for _item_lora in self.lora:
                if _item_lora:
                    _items.append(_item_lora.to_dict())
            _dict['lora'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in nb (list)
        _items = []
        if self.nb:
            for _item_nb in self.nb:
                if _item_nb:
                    _items.append(_item_nb.to_dict())
            _dict['nb'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wifi (list)
        _items = []
        if self.wifi:
            for _item_wifi in self.wifi:
                if _item_wifi:
                    _items.append(_item_wifi.to_dict())
            _dict['wifi'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wifiandsecret (list)
        _items = []
        if self.wifiandsecret:
            for _item_wifiandsecret in self.wifiandsecret:
                if _item_wifiandsecret:
                    _items.append(_item_wifiandsecret.to_dict())
            _dict['wifiandsecret'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArduinoArduinoconnectionsV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "catm1": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["catm1"]] if obj.get("catm1") is not None else None,
            "cellular": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["cellular"]] if obj.get("cellular") is not None else None,
            "eth": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["eth"]] if obj.get("eth") is not None else None,
            "gsm": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["gsm"]] if obj.get("gsm") is not None else None,
            "lora": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["lora"]] if obj.get("lora") is not None else None,
            "nb": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["nb"]] if obj.get("nb") is not None else None,
            "wifi": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["wifi"]] if obj.get("wifi") is not None else None,
            "wifiandsecret": [ArduinoCredentialsv1.from_dict(_item) for _item in obj["wifiandsecret"]] if obj.get("wifiandsecret") is not None else None
        })
        return _obj


