# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from iot_api_client.models.arduino_templatevariable import ArduinoTemplatevariable

class ArduinoWidgetv2template(BaseModel):
    """
    ArduinoWidgetv2template media type (default view)
    """
    height: StrictInt = Field(..., description="Widget current height for desktop")
    height_mobile: Optional[StrictInt] = Field(None, description="Widget current height for mobile")
    name: Optional[StrictStr] = Field(None, description="The name of the widget")
    options: Dict[str, Any] = Field(..., description="Widget options")
    type: StrictStr = Field(..., description="The type of the widget")
    variables: Optional[conlist(ArduinoTemplatevariable)] = Field(None, description="ArduinoTemplatevariableCollection is the media type for an array of ArduinoTemplatevariable (default view)")
    width: StrictInt = Field(..., description="Widget current width for desktop")
    width_mobile: Optional[StrictInt] = Field(None, description="Widget current width for mobile")
    x: StrictInt = Field(..., description="Widget x position for desktop")
    x_mobile: Optional[StrictInt] = Field(None, description="Widget x position for mobile")
    y: StrictInt = Field(..., description="Widget y position for desktop")
    y_mobile: Optional[StrictInt] = Field(None, description="Widget y position for mobile")
    __properties = ["height", "height_mobile", "name", "options", "type", "variables", "width", "width_mobile", "x", "x_mobile", "y", "y_mobile"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ArduinoWidgetv2template:
        """Create an instance of ArduinoWidgetv2template from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in variables (list)
        _items = []
        if self.variables:
            for _item in self.variables:
                if _item:
                    _items.append(_item.to_dict())
            _dict['variables'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ArduinoWidgetv2template:
        """Create an instance of ArduinoWidgetv2template from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ArduinoWidgetv2template.parse_obj(obj)

        _obj = ArduinoWidgetv2template.parse_obj({
            "height": obj.get("height"),
            "height_mobile": obj.get("height_mobile"),
            "name": obj.get("name"),
            "options": obj.get("options"),
            "type": obj.get("type"),
            "variables": [ArduinoTemplatevariable.from_dict(_item) for _item in obj.get("variables")] if obj.get("variables") is not None else None,
            "width": obj.get("width"),
            "width_mobile": obj.get("width_mobile"),
            "x": obj.get("x"),
            "x_mobile": obj.get("x_mobile"),
            "y": obj.get("y"),
            "y_mobile": obj.get("y_mobile")
        })
        return _obj


