# coding: utf-8

"""
    Arduino IoT Cloud API

    Provides a set of endpoints to manage Arduino IoT Cloud **Devices**, **Things**, **Properties** and **Timeseries**. This API can be called just with any HTTP Client, or using one of these clients:  * [Javascript NPM package](https://www.npmjs.com/package/@arduino/arduino-iot-client)  * [Python PYPI Package](https://pypi.org/project/arduino-iot-client/)  * [Golang Module](https://github.com/arduino/iot-client-go)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field, StrictStr

class ArduinoDevicev2SimpleProperties(BaseModel):
    """
    ArduinoDevicev2SimpleProperties media type (default view)
    """
    name: StrictStr = Field(..., description="The name of the property")
    updated_at: datetime = Field(..., description="Update date of the property")
    value: Optional[Any] = Field(..., description="Value of the property")
    __properties = ["name", "updated_at", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ArduinoDevicev2SimpleProperties:
        """Create an instance of ArduinoDevicev2SimpleProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if value (nullable) is None
        # and __fields_set__ contains the field
        if self.value is None and "value" in self.__fields_set__:
            _dict['value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ArduinoDevicev2SimpleProperties:
        """Create an instance of ArduinoDevicev2SimpleProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ArduinoDevicev2SimpleProperties.parse_obj(obj)

        _obj = ArduinoDevicev2SimpleProperties.parse_obj({
            "name": obj.get("name"),
            "updated_at": obj.get("updated_at"),
            "value": obj.get("value")
        })
        return _obj


